// mock simples para o front rodar sem depender de API por enquanto

// unidades
const unidades = [
  {
    id: 1,
    nome: "Recife Centro",
    endereco: "Rua da Aurora, 247 — Boa Vista, Recife - PE",
    telefone: "(81) 3333-1001",
    horario: "07:00 – 22:00",
    aberta: true,
    tipo: "completa",
    categorias: ["cafe", "cuscuz", "tapioca", "sucos", "doces", "junino"],
  },
  {
    id: 2,
    nome: "Fortaleza Aldeota",
    endereco: "Av. Dom Luís, 500 — Aldeota, Fortaleza - CE",
    telefone: "(85) 3333-2002",
    horario: "07:00 – 21:00",
    aberta: true,
    tipo: "completa",
    categorias: ["cafe", "cuscuz", "tapioca", "sucos", "doces"],
  },
  {
    id: 3,
    nome: "São Paulo Pinheiros",
    endereco: "Rua dos Pinheiros, 840 — Pinheiros, São Paulo - SP",
    telefone: "(11) 3333-3003",
    horario: "07:00 – 20:00",
    aberta: true,
    tipo: "reduzida",
    categorias: ["cafe", "cuscuz", "tapioca", "sucos"],
  },
  {
    id: 4,
    nome: "Salvador Pelourinho",
    endereco: "Largo do Pelourinho, 12 — Centro, Salvador - BA",
    telefone: "(71) 3333-4004",
    horario: "08:00 – 22:00",
    aberta: false,
    tipo: "completa",
    categorias: ["cafe", "cuscuz", "tapioca", "sucos", "doces"],
  },
  {
    id: 5,
    nome: "Maceió Centro",
    endereco: "Av. Duque de Caxias, 118 — Centro, Maceió - AL",
    telefone: "(82) 3333-5005",
    horario: "07:00 – 21:00",
    aberta: true,
    tipo: "completa",
    categorias: ["cafe", "cuscuz", "tapioca", "sucos", "doces"],
  },
];

// cardápio
const produtos = [
  // café da manhã
  {
    id: 101,
    nome: "Café com Leite Nordestino",
    descricao: "Café passado na hora com leite integral quentinho",
    preco: 7.0,
    categoria: "cafe",
    imagem: "assets/img/produtos/cafe-leite.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  {
    id: 102,
    nome: "Tapioca de Queijo Coalho",
    descricao: "Tapioca crocante recheada com queijo coalho derretido",
    preco: 12.0,
    categoria: "tapioca",
    imagem: "assets/img/produtos/tapioca-queijo.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  {
    id: 103,
    nome: "Bolo de Macaxeira",
    descricao:
      "Bolo úmido de macaxeira com coco ralado, receita da Dona Francisca",
    preco: 9.0,
    categoria: "doces",
    imagem: "assets/img/produtos/bolo-macaxeira.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 4, 5],
  },
  // cuscuz
  {
    id: 201,
    nome: "Cuscuz Simples",
    descricao: "Cuscuz de milho no vapor, servido com manteiga de garrafa",
    preco: 10.0,
    categoria: "cuscuz",
    imagem: "assets/img/produtos/cuscuz-simples.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  {
    id: 202,
    nome: "Cuscuz Recheado Completo",
    descricao: "Cuscuz com ovo mexido, charque desfiado, queijo e manteiga",
    preco: 18.0,
    categoria: "cuscuz",
    imagem: "assets/img/produtos/cuscuz-recheado.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 4, 5],
  },
  {
    id: 203,
    nome: "Cuscuz Vegetariano",
    descricao: "Cuscuz com legumes salteados, azeite e ervas finas",
    preco: 15.0,
    categoria: "cuscuz",
    imagem: "assets/img/produtos/cuscuz-vegano.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  // tapioca
  {
    id: 301,
    nome: "Tapioca de Frango com Catupiry",
    descricao: "Frango desfiado temperado com ervas e catupiry cremoso",
    preco: 15.0,
    categoria: "tapioca",
    imagem: "assets/img/produtos/tapioca-frango.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  {
    id: 302,
    nome: "Tapioca Doce de Coco",
    descricao: "Tapioca com coco fresco ralado e mel de engenho",
    preco: 11.0,
    categoria: "tapioca",
    imagem: "assets/img/produtos/tapioca-coco.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 4, 5],
  },
  {
    id: 303,
    nome: "Tapioca de Camarão",
    descricao: "Camarão refogado com pimentões e coentro fresco",
    preco: 22.0,
    categoria: "tapioca",
    imagem: "assets/img/produtos/tapioca-camarao.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 4, 5],
  },
  // sucos regionais
  {
    id: 401,
    nome: "Suco de Cajá",
    descricao: "Cajá gelado batido na hora, levemente adoçado",
    preco: 9.0,
    categoria: "sucos",
    imagem: "assets/img/produtos/suco-caja.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  {
    id: 402,
    nome: "Suco de Umbu",
    descricao: "Umbu fresco da caatinga, doce e levemente ácido",
    preco: 9.0,
    categoria: "sucos",
    imagem: "assets/img/produtos/suco-umbu.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 4, 5],
  },
  {
    id: 403,
    nome: "Suco de Graviola",
    descricao: "Graviola cremosa batida com leite de coco",
    preco: 11.0,
    categoria: "sucos",
    imagem: "assets/img/produtos/suco-graviola.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  // doces
  {
    id: 501,
    nome: "Pamonha de Milho Verde",
    descricao: "Pamonha tradicional doce, embrulhada em palha de milho",
    preco: 8.0,
    categoria: "doces",
    imagem: "assets/img/produtos/pamonha.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 4, 5],
  },
  {
    id: 502,
    nome: "Cocada Cremosa",
    descricao: "Cocada mole com leite condensado, faz na hora",
    preco: 7.0,
    categoria: "doces",
    imagem: "assets/img/produtos/cocada.jpg",
    disponivel: true,
    sazonal: false,
    unidades: [1, 2, 3, 4, 5],
  },
  // especial junino
  {
    id: 601,
    nome: "Canjica Festiva",
    descricao: "Canjica branca com amendoim torrado, leite de coco e canela",
    preco: 14.0,
    categoria: "junino",
    imagem: "assets/img/produtos/canjica.jpg",
    disponivel: true,
    sazonal: true,
    unidades: [1, 2, 4, 5],
  },
  {
    id: 602,
    nome: "Mungunzá Nordestino",
    descricao: "Milho branco cozido no leite de coco com especiarias",
    preco: 13.0,
    categoria: "junino",
    imagem: "assets/img/produtos/mungunza.jpg",
    disponivel: true,
    sazonal: true,
    unidades: [1, 4, 5],
  },
  {
    id: 603,
    nome: "Pé de Moleque",
    descricao: "Amendoim torrado com rapadura, crocante e artesanal",
    preco: 6.0,
    categoria: "junino",
    imagem: "assets/img/produtos/pe-de-moleque.jpg",
    disponivel: true,
    sazonal: true,
    unidades: [1, 2, 3, 4, 5],
  },
];

// fidelidade
const recompensas = [
  {
    id: 1,
    nome: "Café Gratuito",
    descricao: "Um café com leite nordestino à sua escolha",
    pontos: 100,
    emoji: "☕",
    disponivel: true,
  },
  {
    id: 2,
    nome: "Combo com 50% OFF",
    descricao: "50% de desconto em qualquer combo do cardápio",
    pontos: 200,
    emoji: "🍽️",
    disponivel: true,
  },
  {
    id: 3,
    nome: "Tapioca Grátis",
    descricao: "Qualquer tapioca do cardápio, por nossa conta",
    pontos: 350,
    emoji: "🫓",
    disponivel: true,
  },
  {
    id: 4,
    nome: "Cuscuz Especial + Suco",
    descricao: "Cuscuz recheado completo com suco regional à escolha",
    pontos: 500,
    emoji: "🌽",
    disponivel: true,
  },
  {
    id: 5,
    nome: "Almoço para 2",
    descricao: "Dois combos completos com sobremesa e suco",
    pontos: 1000,
    emoji: "👨‍👩‍👧",
    disponivel: true,
  },
];

// cupons
const cupons = [
  {
    codigo: "JUNHO10",
    descricao: "10% de desconto na festa junina",
    tipo: "percentual",
    valor: 10,
    ativo: true,
  },
  {
    codigo: "BEMVINDO5",
    descricao: "R$5 de desconto no primeiro pedido",
    tipo: "fixo",
    valor: 5,
    ativo: true,
  },
  {
    codigo: "RAIZES15",
    descricao: "15% OFF para clientes fiéis",
    tipo: "percentual",
    valor: 15,
    ativo: true,
  },
];

// usuário de exemplo
const usuarioDemo = {
  id: 1,
  nome: "João Silva",
  email: "joao@email.com",
  senha: "123456",
  telefone: "(11) 99999-1234",
  pontos: 247,
  nivel: "Ouro",
  consentimentos: {
    lgpd: true,
    marketing: true,
    personalizacao: true,
  },
  historicoPedidos: [
    {
      id: "2845",
      data: "2026-06-01",
      unidade: "São Paulo Pinheiros",
      total: 33.0,
      pontos: 33,
      itens: ["Cuscuz Simples", "Tapioca de Queijo Coalho", "Suco de Cajá"],
    },
    {
      id: "2791",
      data: "2026-05-24",
      unidade: "São Paulo Pinheiros",
      total: 27.0,
      pontos: 27,
      itens: ["Cuscuz Vegetariano", "Suco de Graviola"],
    },
    {
      id: "2720",
      data: "2026-05-17",
      unidade: "São Paulo Pinheiros",
      total: 19.0,
      pontos: 19,
      itens: ["Tapioca de Frango com Catupiry", "Suco de Cajá"],
    },
  ],
};

// labels das abas do cardápio
const categorias = [
  { id: "todos", label: "Todos" },
  { id: "cafe", label: "☕ Café da Manhã" },
  { id: "cuscuz", label: "🌽 Cuscuz" },
  { id: "tapioca", label: "🫓 Tapioca" },
  { id: "sucos", label: "🥤 Sucos" },
  { id: "doces", label: "🍮 Doces" },
  { id: "junino", label: "🎉 Especial Junino" },
];
